driverClassName=com.mysql.cj.jdbc.Driver
url=jdbc:mysql://127.0.0.1:3306/itcast?useServerPrepStmts=true&serverTimezone=UTC
username=ubuntu
password=123456
#???????
initialSize=5
#?????
maxSize=10
#??????
maxWait=3000
