server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3307/redis_exercise?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8&allowPublicKeyRetrieval=true
    username: root
    password: 123456

  data:
    redis:
      host: 127.0.0.1
      port: 6380
      password: 123321
      lettuce:
        pool:
          max-wait: 200ms
          max-idle: 8
          min-idle: 0
          max-active: 8
#NOTE debug日志需要进行配置
logging:
  level:
    com.nanxinda: debug



