#NOTE 2.配置文件
spring:
  data:
    redis:
      host: 127.0.0.1
      port: 6380
      password: 123321
      lettuce:
        pool:
          max-active: 8 #最大连接
          max-idle: 8 #最大空闲连接
          min-idle: 0 #最小空闲连接
          max-wait: 200ms #连接等待时间

