#三种格式properties、yaml、yml都可以修改服务器的端口，但是优先级
#为properties>yml>yaml

#yaml
#YAML（YAML Ain't Markup Language），种数据序列化格式
#优点:
#  •容易阅读
#  •容易与脚本语言交互
#  •以数据为核心，重数据轻格式
#YAML文件扩展名
#  •yml（主流）
#  •yaml

#  yaml语法规则
#  • 大小写敏感
#  • 属性层级关系使用多行描述，每行结尾使用冒号结束
#  • 使用缩进表示层级关系，同层级左侧对齐，只允许使用空格（不允许使Tab键表示缩进）
#  • 属性值前面添加空格（属性名与属性值之间使用冒号+空格作为分隔）
#  • #表示注释

# yaml数组数据
# •数组数据在数据书写位置下方使用减号作为数据开始符号，每行书写一个数据，减号与数据空格分隔
server:
  port: 84
enterprise:
  name: itcast
  age: 16
  tel: 18114636782
  subject:
    - Java
    - agent
    - 监控
    - 运维